; PlatformIO Project Configuration File for standalone Cardulator repository

[platformio]
default_envs = cardputer
src_dir = src

[env:cardputer]
platform = espressif32
board = m5stack-stamps3
framework = arduino
monitor_speed = 115200
build_unflags = -std=gnu++11 -std=gnu++14 -std=gnu++17 -std=c++11 -std=c++14 -std=c++17 -fno-rtti
build_flags = 
	-std=gnu++2a
	-Wno-attributes
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DCONFIG_ARDUINO_LOOP_STACK_SIZE=32768
	-DUNIT_TEST=1
platform_packages = 
	framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#2.0.17
	toolchain-xtensa-esp32s3 @ 12.2.0+20230208
lib_extra_dirs = 
	lib
extra_scripts = pre:build_tinyexpr.py

[env:native]
platform = native
build_unflags = -std=gnu++11
build_flags = 
	-std=gnu++2a
	-O0
	-DUNITY_INCLUDE_DOUBLE
	-DUNIT_TEST=1
	-w
lib_extra_dirs = 
	lib
extra_scripts = pre:build_tinyexpr.py
